// Generated by CoffeeScript 1.8.0
(function() {
  exports.parse = function(input, result) {
    var idx, key, line, linenumber, shift, value, _i, _len, _ref;
    if (result == null) {
      result = {};
    }
    _ref = input.split('\n');
    for (linenumber = _i = 0, _len = _ref.length; _i < _len; linenumber = ++_i) {
      line = _ref[linenumber];
      line = line.trim();
      if (!line) {
        continue;
      }
      shift = 1;
      while (true) {
        idx = line.indexOf('=', shift);
        if (idx === -1) {
          throw new Error("'=' not found on line " + (linenumber + 1));
        }
        if ('\\' !== line.charAt(idx - 1)) {
          key = (line.substr(0, idx)).split('\\=').join('=');
          value = line.substr(idx + 1);
          break;
        }
        shift = idx + 1;
      }
      result[key.trimRight()] = value.trimLeft();
    }
    return result;
  };

}).call(this);
