// Generated by CoffeeScript 1.8.0
(function() {
  var debug, getAcceptLanguage, getInstance, middleware,
    __slice = [].slice;

  debug = require('debug')('i18n');

  getAcceptLanguage = require("./utils").getAcceptLanguage;

  getInstance = require("./translator").getInstance;

  middleware = function(_arg) {
    var cookie, directory, env, fallback, nsSeparator, query, translator;
    cookie = _arg.cookie, directory = _arg.directory, fallback = _arg.fallback, nsSeparator = _arg.nsSeparator, query = _arg.query;
    if (!directory) {
      throw new Error("you hava to specify directory for locales");
    }
    if (!fallback) {
      throw new Error("you hava to specify a fallback language");
    }
    if (cookie == null) {
      cookie = 'lang';
    }
    if (query == null) {
      query = 'set-lang';
    }
    if (nsSeparator == null) {
      nsSeparator = ':';
    }
    env = process.env.NODE_ENV || 'development';
    translator = getInstance(nsSeparator);
    translator.load(directory);
    debug("languages loaded: " + (translator.speaks()));
    return function(req, res, next) {
      var lang;
      if (env === "development") {
        translator.load(directory);
      }
      lang = req.query[query] || req.cookies[cookie] || translator["try"](getAcceptLanguage(req.headers['accept-language']));
      if (!translator.knows(lang)) {
        lang = fallback;
        debug("fallback to " + lang);
      }
      res.locals._ = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return translator.translate.apply(translator, [lang].concat(__slice.call(args)));
      };
      res.locals.__ = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return translator.translatePlural.apply(translator, [lang].concat(__slice.call(args)));
      };
      res.locals.lang = lang;
      req.lang = lang;
      if (req.cookies[cookie] !== lang) {
        res.cookie(cookie, lang, {
          maxAge: 31536000000
        });
        debug("set cookie lang=" + lang);
      }
      return next();
    };
  };

  module.exports = {
    middleware: middleware
  };

}).call(this);
